
gazebo_ros_control:
  pid_gains:
    jnt_motor_left_to_wheel_left:
      p: 10
      i: 0.01
      d: 1
    jnt_motor_right_to_wheel_right:
      p: 10
      i: 0.01
      d: 1

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

auger_pos_controller:
  type: effort_controllers/JointVelocityController
  joint: jnt_base_frame_to_auger
  pid: {p: 10.0, i: 0.01, d: 1.0}

drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel  : 'jnt_motor_left_to_wheel_left'
  right_wheel : 'jnt_motor_right_to_wheel_right'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, .001, 1000000., 1000000., 1000000., 1000.]
  twist_covariance_diagonal: [0.001, .001, 1000000., 1000000., 1000000., 1000.]
  wheel_radius: 0.051
  wheel_seperation: 0.3556
  base_frame_id: base_link
  pid: {p: 10.0, i: 0.01, d: 1.0}
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 4.0  # m/s
      min_velocity           : -4 # m/s
      has_acceleration_limits: true
      max_acceleration       : 4  # m/s^2
      min_acceleration       : -4 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 5.0  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.7  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.5  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 2.5  # rad/s^3
