<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ansrr">

  <xacro:property name="box_x" value="0.4572"/>
  <xacro:property name="box_y" value="0.4572"/>
  <xacro:property name="box_z" value="0.1524"/>

  <xacro:property name="box_mass" value= "1"/>
  <xacro:property name="box_ixx" value= "0.01935"/>
  <xacro:property name="box_iyy" value= "0.01935"/>
  <xacro:property name="box_izz" value= "0.03483"/>

  <xacro:property name="length" value="0.0508"/>
  <xacro:property name="wheel_radius" value="0.0762"/>

  <xacro:property name="wheel_mass" value= "0.1"/>
  <xacro:property name="wheel_ixx" value= "5.685e-4"/>
  <xacro:property name="wheel_iyy" value= "5.685e-4"/>
  <xacro:property name="wheel_izz" value= "2.903e-4"/>

  <xacro:property name="front_x" value="-0.0254"/>
  <xacro:property name="rear_x" value="0.1524"/>
  <xacro:property name="wheel_y" value="0.2032"/>
  <xacro:property name="wheel_z" value="-0.06096"/>



  <xacro:macro name="geo_box">
    <geometry>
      <box size="${box_x} ${box_y} ${box_z}"/>
    </geometry>
  </xacro:macro>

  <xacro:macro name="inertia_macro" params="mass ixx iyy izz">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="${ixx}" iyy="${iyy}" izz="${izz}" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="wheel" params="w_name x y z">
    <link name="${w_name}">
      <visual>
        <geometry>
          <cylinder length="${length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <xacro:inertia_macro mass="${wheel_mass}" ixx="${wheel_ixx}" iyy="${wheel_iyy}" izz="${wheel_izz}"/>
    </link>
    <joint name="base_to_${w_name}" type="continuous">
      <axis xyz="0 0 1"/>
      <parent link="base_link"/>
      <child link="${w_name}"/>
      <origin rpy="1.5708 0 0" xyz="${x} ${y} ${z}"/>
    </joint>
  </xacro:macro>

  <!-- Start of URDF-->
  <link name="base_link">
    <visual>
      <xacro:geo_box />
      <material name="silver">
        <color rgba="0.75 0.75 0.75 1"/>
      </material>
    </visual>
    <collision>
      <xacro:geo_box />
    </collision>
    <xacro:inertia_macro mass="1" ixx= "${box_ixx}" iyy="${box_iyy}" izz="${box_izz}"/>
  </link>
  <xacro:wheel w_name="left_front" x="${front_x}" y="-${wheel_y}" z="${wheel_z}"/>
  <xacro:wheel w_name="left_rear" x="${rear_x}" y="-${wheel_y}" z="${wheel_z}"/>
  <xacro:wheel w_name="right_front" x="${front_x}" y="${wheel_y}" z="${wheel_z}"/>
  <xacro:wheel w_name="right_rear" x="${rear_x}" y="${wheel_y}" z="${wheel_z}"/>

  <link name="fake_lidar">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <xacro:inertia_macro mass="0.05" ixx="0.01" iyy="0.01" izz="0.01"/>
  </link>
  <joint name="base_to_fake_lidar" type="fixed">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="fake_lidar"/>
    <origin rpy="0 0 3.14" xyz="-.2286 0 0.1"/>
  </joint>


  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <leftJoint>base_to_left_rear</leftJoint>
      <rightJoint>base_to_right_rear</rightJoint>
      <robotBaseFrame>base_link</robotBaseFrame>
      <wheelSeparation>0.4064</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <publishWheelJointState>true</publishWheelJointState>
    </plugin>
    <plugin name="differential_drive_controller_1" filename="libgazebo_ros_diff_drive.so">
      <leftJoint>base_to_left_front</leftJoint>
      <rightJoint>base_to_right_front</rightJoint>
      <robotBaseFrame>base_link</robotBaseFrame>
      <wheelSeparation>0.4064</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <publishWheelJointState>true</publishWheelJointState>
    </plugin>

  </gazebo>
  <gazebo reference="fake_lidar">
    <sensor name="lds_lfcd_sensor" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>0</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>6.28</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>10</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_lds_lfcd_controller  " filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>fake_lidar</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <link name="fake_ultrasound">
    <visual>
      <geometry>
        <box size="0.01 0.05 0.01"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>model
    <xacro:inertia_macro mass="0.05" ixx="0.01" iyy="0.01" izz="0.01"/>
  </link>
  <joint name="base_to_fake_ultrasound" type="fixed">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="fake_ultrasound"/>
    <origin rpy="0 0.2 3.14" xyz="-.2286 0 0.16"/>
  </joint>

  <gazebo reference="fake_ultrasound">
    <sensor name="us" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>1</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>4</samples>
            <resolution>4</resolution>
            <min_angle>-0.5235</min_angle>
            <max_angle>0.5235</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>1.3</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_us_lfcd_controller  " filename="libgazebo_ros_laser.so">
        <topicName>us_scan</topicName>
        <frameName>fake_ultrasound</frameName>
      </plugin>
    </sensor>
  </gazebo>

</robot>
